FROM ghcr.io/foundry-rs/foundry

WORKDIR /develop
COPY . .

RUN forge b --skip test
#RUN forge script script/deploy.local.s.sol:Local -f http://anvil:8545 --broadcast
ENTRYPOINT ["tail", "-f", "/dev/null"]